// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs7waHJDQUWtKr4PE19M8DBJu7Z34oiew',
    appId: '1:362471044038:web:c8b598f923b17bfeedf8c7',
    messagingSenderId: '362471044038',
    projectId: 'gharsathi-da6fc',
    authDomain: 'gharsathi-da6fc.firebaseapp.com',
    storageBucket: 'gharsathi-da6fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSpiutyADTrFhP8nAM6tgZz-aVa41xnjE',
    appId: '1:362471044038:android:571fc7d61f8a563fedf8c7',
    messagingSenderId: '362471044038',
    projectId: 'gharsathi-da6fc',
    storageBucket: 'gharsathi-da6fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClTWerJXVHrrsCFnmOZw_ZQvz5kvS63ys',
    appId: '1:362471044038:ios:944392a39a4897d2edf8c7',
    messagingSenderId: '362471044038',
    projectId: 'gharsathi-da6fc',
    storageBucket: 'gharsathi-da6fc.appspot.com',
    iosBundleId: 'com.example.gharsathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClTWerJXVHrrsCFnmOZw_ZQvz5kvS63ys',
    appId: '1:362471044038:ios:944392a39a4897d2edf8c7',
    messagingSenderId: '362471044038',
    projectId: 'gharsathi-da6fc',
    storageBucket: 'gharsathi-da6fc.appspot.com',
    iosBundleId: 'com.example.gharsathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs7waHJDQUWtKr4PE19M8DBJu7Z34oiew',
    appId: '1:362471044038:web:8b304b4d5a61c58fedf8c7',
    messagingSenderId: '362471044038',
    projectId: 'gharsathi-da6fc',
    authDomain: 'gharsathi-da6fc.firebaseapp.com',
    storageBucket: 'gharsathi-da6fc.appspot.com',
  );
}
